language: python
python:
- '3.2'
- '3.3'
- '3.4'
install:
- pip install -r requirements.txt
- python setup.py install
script: python -m unittest -v test/test_prov.py
deploy:
  provider: pypi
  user: zednik
  password:
    secure: UNheuOR8LP8MFsFLql72kkkjdxvxmJV9cYyRDzF/0KOWCkgQ73LgQqJoL9Gvg8urVdcXzJJ3XchXiGC7ntT8/TS12ldU239ysKon0tVgel4S3Wmt+xnjCnjOSuVl8kfnl6LD28y39Rw6vUBHuCWeksPjJBc6jvkTKuOBVJQfdHw=
  on:
    tags: true
